spring.application.name=employee-management-system

spring.datasource.url=jdbc:mysql://${MYSQLHOST:nozomi.proxy.rlwy.net}:${MYSQLPORT:31420}/${MYSQLDATABASE:railway}
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:dnaskvFvlrPKSAJHgojwKDVZhrzrEwty}

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=${PORT:8080}
